######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 11 16:15:08 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

unix{
   CONFIG+=link_pkgconfig
   PKGCONFIG+=opencv
}
QT+=gui widgets
